apiVersion : apps/v1
kind: Deployment
metadata:
  name: web-cv-deployment
  labels: 
    app : web-cv-minikube
spec:
  replicas: 3
  selector:
    matchLabels:
      project: web-app
  template:
    metadata:
      labels:
        project: web-app
    spec:
      containers:
      - name: web-cv-container
        image: jassonaxe/cv:v1.0.2
        ports:
          - containerPort: 80
