apiVersion : apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels: 
    app : my-minikube-deployments
spec:
  replicas: 3
  selector:
    matchLabels:
      project: web-app
  template:
    metadata:
      labels:
        project: web-app
    spec:
      containers:
      - name: web-cv
        image: jassonaxe/cv:v1.0.2
        ports:
          - containerPort: 80
