apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  labels:
    env : prod
    owner: JohnDoe
spec:
  selector:
    project: web-app
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 443
      targetPort: 443
  type: ClasterIP