apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels: 
    app : {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: web-app
  template:
    metadata:
      labels:
        project: web-app
    spec:
      containers:
      - name: web-cv
        image: {{ .Values.container.image }}
        ports:
          - containerPort: 80
