apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    env : prod
    owner: JohnDoe
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 443
      targetPort: 443
  type: ClusterIP #LoadBalancer