apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-cv-autoscaling
  labels:
    app: my-cv-app
    env: prod
    owner: JohnDoe
spec:
  replicas: 2
  selector:
    matchLabels:
      project: cv-project
  template:
    metadata:
      labels:
        project: cv-project
    spec:
      containers:
        - name: web-cv-v1-0-2
          image: jassonaxe/cv:v1.0.2
          ports:
            - containerPort: 443

---
#Replicas config had better create in separate file

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cv-project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-cv-autoscaling
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web-cv-service
  labels:
    env : prod
    owner: JohnDoe
spec:
  selector:
    project: cv-project
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 443
      targetPort: 8081
  type: ClusterIP #LoadBalancer
