apiVersion : v1
name       : App-HelmChart
description: My Helm chart for Kubernetes
type       : application
version    : v3.10.1  #This is the Helm Chart version
appVersion : "v1.0.2" #This is the version of the application being deployed

keywords:
  - nginx
  - http
  - https
  - johndoe

maintainers:
  - name : JohnDoe
    email: johndoe@gmail.com
    url  : johndoe.com